#!/usr/bin/env bash
# deploy-appflowy.sh — Deploy AppFlowy Cloud to a client's VPS
#
# Usage:
#   ./scripts/deploy-appflowy.sh <client_name> <vps_ip>
#
# Example:
#   ./scripts/deploy-appflowy.sh grigory 89.167.22.91
#
# Prerequisites:
#   - SSH key access to root@<vps_ip>
#   - Docker & Docker Compose on VPS (installed automatically if missing)

set -euo pipefail

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'
YELLOW='\033[1;33m'; NC='\033[0m'
header() { echo -e "\n${BLUE}━━━ $1 ━━━${NC}"; }
ok()     { echo -e "${GREEN}✓ $1${NC}"; }
warn()   { echo -e "${YELLOW}⚠ $1${NC}"; }
fail()   { echo -e "${RED}✗ $1${NC}"; exit 1; }

# ── Arguments ────────────────────────────────────────────────
CLIENT="${1:?Usage: deploy-appflowy.sh <client_name> <vps_ip>}"
VPS="${2:?Usage: deploy-appflowy.sh <client_name> <vps_ip>}"
SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APPFLOWY_DIR="${SCRIPT_DIR}/appflowy"
CLIENT_DIR="${SCRIPT_DIR}/clients/${CLIENT}"

# Validate
[[ -d "${APPFLOWY_DIR}" ]] || fail "appflowy/ directory not found"
[[ -f "${APPFLOWY_DIR}/docker-compose.yml" ]] || fail "docker-compose.yml not found"

# ── Step 1: Check SSH ────────────────────────────────────────
header "1/9 Checking SSH access to ${VPS}"
ssh -o ConnectTimeout=5 -o BatchMode=yes "root@${VPS}" "echo ok" >/dev/null 2>&1 \
  || fail "Cannot SSH to root@${VPS}"
ok "SSH access verified"

# ── Step 2: Check/Install Docker ─────────────────────────────
header "2/9 Checking Docker on VPS"
if ssh "root@${VPS}" "command -v docker >/dev/null 2>&1"; then
  ok "Docker already installed"
else
  warn "Docker not found, installing..."
  ssh "root@${VPS}" "curl -fsSL https://get.docker.com | sh"
  ok "Docker installed"
fi

if ssh "root@${VPS}" "docker compose version >/dev/null 2>&1"; then
  ok "Docker Compose available"
else
  fail "Docker Compose not available (requires Docker Engine 20.10+)"
fi

# ── Step 3: Generate Secrets ─────────────────────────────────
header "3/9 Generating secrets"
gen_secret() { openssl rand -hex 24; }
gen_jwt_secret() { openssl rand -hex 32; }

POSTGRES_PASSWORD="$(gen_secret)"
GOTRUE_JWT_SECRET="$(gen_jwt_secret)"
GOTRUE_ADMIN_PASSWORD="$(gen_secret)"
AWS_ACCESS_KEY="$(gen_secret)"
AWS_SECRET="$(gen_secret)"
AGENT_PASSWORD="$(gen_secret)"

# Derive FQDN from client config if available
if [[ -f "${CLIENT_DIR}/config.md" ]]; then
  FQDN=$(grep -oP 'https://\K[^/\s]+' "${CLIENT_DIR}/config.md" | head -1) || true
fi
FQDN="${FQDN:-${CLIENT}.belagent.com}"

ok "Secrets generated for ${FQDN}"

# ── Step 4: Deploy files to VPS ──────────────────────────────
header "4/9 Deploying AppFlowy files to VPS"
ssh "root@${VPS}" "mkdir -p /opt/appflowy"

# Copy docker-compose.yml and nginx.conf
scp "${APPFLOWY_DIR}/docker-compose.yml" "root@${VPS}:/opt/appflowy/"
scp "${APPFLOWY_DIR}/nginx.conf" "root@${VPS}:/opt/appflowy/"

# Generate .env on VPS
ssh "root@${VPS}" "cat > /opt/appflowy/.env << 'ENVEOF'
# Auto-generated by deploy-appflowy.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
FQDN=${FQDN}
SCHEME=https
WS_SCHEME=wss
NGINX_PORT=8025

POSTGRES_USER=appflowy
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=appflowy

AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
AWS_SECRET=${AWS_SECRET}

GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
GOTRUE_JWT_EXP=604800
GOTRUE_ADMIN_EMAIL=admin@${FQDN}
GOTRUE_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD}
GOTRUE_MAILER_AUTOCONFIRM=true
GOTRUE_DISABLE_SIGNUP=true

APPFLOWY_S3_BUCKET=appflowy
APPFLOWY_DATABASE_MAX_CONNECTIONS=20
APPFLOWY_WEBSOCKET_MAILBOX_SIZE=2000
RUST_LOG=info

APPFLOWY_AGENT_EMAIL=agent@local.belagent
APPFLOWY_AGENT_PASSWORD=${AGENT_PASSWORD}
ENVEOF"

ok "Files deployed to /opt/appflowy/"

# ── Step 5: Start Docker Stack ───────────────────────────────
header "5/9 Starting AppFlowy Docker stack"
ssh "root@${VPS}" "cd /opt/appflowy && docker compose pull --quiet && docker compose up -d"
ok "Docker stack starting"

# ── Step 6: Wait for Health ──────────────────────────────────
header "6/9 Waiting for AppFlowy Cloud to be healthy"
TIMEOUT=180
ELAPSED=0
while [[ $ELAPSED -lt $TIMEOUT ]]; do
  if ssh "root@${VPS}" "curl -sf http://localhost:8025/api/health" >/dev/null 2>&1; then
    ok "AppFlowy Cloud healthy after ${ELAPSED}s"
    break
  fi
  sleep 5
  ELAPSED=$((ELAPSED + 5))
  echo -n "."
done
echo
[[ $ELAPSED -lt $TIMEOUT ]] || fail "AppFlowy did not become healthy within ${TIMEOUT}s"

# ── Step 7: Create Agent Service Account ─────────────────────
header "7/9 Creating agent service account"

# Get admin JWT from GoTrue
ADMIN_TOKEN=$(ssh "root@${VPS}" "curl -sf -X POST http://localhost:19999/token?grant_type=password \
  -H 'Content-Type: application/json' \
  -d '{\"email\":\"admin@${FQDN}\",\"password\":\"${GOTRUE_ADMIN_PASSWORD}\"}'" \
  | python3 -c "import sys,json; print(json.load(sys.stdin)['access_token'])" 2>/dev/null) || true

if [[ -n "${ADMIN_TOKEN:-}" ]]; then
  # Create agent user
  ssh "root@${VPS}" "curl -sf -X POST http://localhost:19999/admin/users \
    -H 'Authorization: Bearer ${ADMIN_TOKEN}' \
    -H 'Content-Type: application/json' \
    -d '{\"email\":\"agent@local.belagent\",\"password\":\"${AGENT_PASSWORD}\",\"email_confirm\":true}'" >/dev/null 2>&1 \
    && ok "Agent service account created" \
    || warn "Agent account may already exist (ignoring)"
else
  warn "Could not get admin token — create agent account manually"
fi

# ── Step 8: Update belagent nginx ────────────────────────────
header "8/9 Updating belagent nginx config"

# Check if /appflowy/ location already exists
if ssh "root@${VPS}" "grep -q 'appflowy_cloud' /etc/nginx/sites-available/belagent 2>/dev/null"; then
  ok "AppFlowy proxy already in nginx config"
else
  # Add upstream and location before the catch-all location /
  ssh "root@${VPS}" "sed -i '/^server {/a\\
\\n    # AppFlowy Cloud upstream\\n' /etc/nginx/sites-available/belagent"

  # Simpler approach: replace the nginx config entirely
  scp "${SCRIPT_DIR}/memory-server/nginx-belagent.conf" "root@${VPS}:/etc/nginx/sites-available/belagent"
  ok "Nginx config updated with AppFlowy proxy"
fi

# Reload nginx
ssh "root@${VPS}" "nginx -t && systemctl reload nginx" \
  && ok "Nginx reloaded" \
  || fail "Nginx config test failed"

# ── Step 9: Verify & Save ────────────────────────────────────
header "9/9 Verifying deployment"

# Test through nginx
HTTP_CODE=$(ssh "root@${VPS}" "curl -sf -o /dev/null -w '%{http_code}' http://localhost:80/appflowy/" 2>/dev/null) || HTTP_CODE="000"
if [[ "${HTTP_CODE}" == "200" ]] || [[ "${HTTP_CODE}" == "301" ]] || [[ "${HTTP_CODE}" == "302" ]]; then
  ok "AppFlowy accessible at /appflowy/ (HTTP ${HTTP_CODE})"
else
  warn "AppFlowy returned HTTP ${HTTP_CODE} — may need time to fully start"
fi

# Save credentials locally
mkdir -p "${CLIENT_DIR}"
cat > "${CLIENT_DIR}/appflowy-secrets.env" << EOF
# AppFlowy Cloud credentials for ${CLIENT} (${FQDN})
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — this file is gitignored

APPFLOWY_URL=https://${FQDN}/appflowy
APPFLOWY_ADMIN_EMAIL=admin@${FQDN}
APPFLOWY_ADMIN_PASSWORD=${GOTRUE_ADMIN_PASSWORD}
APPFLOWY_AGENT_EMAIL=agent@local.belagent
APPFLOWY_AGENT_PASSWORD=${AGENT_PASSWORD}
GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
AWS_SECRET=${AWS_SECRET}
EOF

ok "Credentials saved to clients/${CLIENT}/appflowy-secrets.env"

# ── Done ─────────────────────────────────────────────────────
echo
echo -e "${GREEN}━━━ AppFlowy deployed for ${CLIENT} ━━━${NC}"
echo -e "  URL:   https://${FQDN}/appflowy/"
echo -e "  Admin: admin@${FQDN}"
echo -e "  Agent: agent@local.belagent"
echo
echo -e "  Verify on VPS:"
echo -e "    docker compose -f /opt/appflowy/docker-compose.yml ps"
echo -e "    curl -s http://localhost:8025/api/health"
echo
